// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 9.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container0").wowSlider({effect:"basic",prev:"",next:"",duration:32*100,delay:33*100,width:304,height:257,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:false,loop:false,bullets:1,caption:false,captionEffect:"parallax",controls:true,controlsThumb:["data0/tooltips/casa1.jpg", "data0/tooltips/casa3.jpg", "data0/tooltips/casa4.jpg", "data0/tooltips/casa2.jpg"],responsive:1,fullScreen:false,gestures:2,onBeforeStep:0,images:0});